class CourInfo {
  final int position;
  final String name;
  final String iconImage;
  final String description;

  CourInfo(this.position,
      {required this.name, required this.iconImage, required this.description});
}

List<CourInfo> courInfo = [
  CourInfo(1,
      name: "Cour 1", iconImage: 'assets/images/logo.png', description: ""),
  CourInfo(2,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(3,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(4,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(5,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(6,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(7,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(9,
      name: "cour 9",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(10,
      name: "cour 10",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(11,
      name: "cour 11",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(12,
      name: "cour 12",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(13,
      name: "cour 13",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(14,
      name: "cour 14",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(15,
      name: "cour 15",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(16,
      name: "cour 16",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(17,
      name: "cour 17",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(18,
      name: "cour 18",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(19,
      name: "cour 19",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(20,
      name: "cour 20",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(21,
      name: "cour 21",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(22,
      name: "cour 22",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(23,
      name: "cour 23",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(24,
      name: "cour 24",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(25,
      name: "cour 25",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(26,
      name: "cour 26",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(27,
      name: "cour 27",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(28,
      name: "cour 28",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(29,
      name: "cour 29",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(30,
      name: "cour 30",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(31,
      name: "cour 31",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(32,
      name: "cour 32",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(33,
      name: "cour 33",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(34,
      name: "cour 34",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(35,
      name: "cour 35",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(36,
      name: "cour 36",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(37,
      name: "cour 37",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(38,
      name: "cour 38",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(39,
      name: "cour 39",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(40,
      name: "cour 40",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
];
