class CourInfo {
  final int position;
  final String name;
  final String iconImage;
  final String description;

  CourInfo(this.position,
      {required this.name, required this.iconImage, required this.description});
}

List<CourInfo> courInfo = [
  CourInfo(1,
      name: "cour 1",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(2,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(3,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(4,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(5,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(6,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(7,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(9,
      name: "cour 1",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(10,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(11,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(12,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(13,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(14,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(15,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(15,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(16,
      name: "cour 1",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(17,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(17,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(18,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(6,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(7,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(1,
      name: "cour 1",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(2,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(3,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(4,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(5,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(6,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(7,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(1,
      name: "cour 1",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(2,
      name: "cour 2",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(3,
      name: "cour 3",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(4,
      name: "cour 4",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(5,
      name: "cour 5",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(6,
      name: "cour 6",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(7,
      name: "cour 7",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
  CourInfo(8,
      name: "cour 8",
      iconImage: 'assets/images/logo.png',
      description: "blablablabla"),
];
